#!/bin/bash

tools/assemble.sh assembly .autograder.missing.files                                    && # Build everything
(cd assembly && ./run-tests -o ../results/results.json -m ../.autograder.missing.files)    # Run the tests!
