CPP_FILES    := $(wildcard *.cpp)
OBJ_FILES    := $(CPP_FILES:.cpp=.o)

CC_FLAGS := -g -O0 -Wall -Werror -Wpedantic --std=c++17 -IUtilities
LD_FLAGS := 

all: run-tests

run-tests: $(OBJ_FILES)
	g++ $(LD_FLAGS) -o $@ $^

%.o: %.cpp
# Build with GROUP subbed out for an ID derived from the contents of the testing file.
# This may cause problems if there are two literally identical test files, but we
# don't anticipate this will happen.
	g++ -c $(CC_FLAGS) -DGROUP=GroupID_$(shell md5sum $< | awk '{print $$1}') -o $@ $<


.PHONY: clean

clean:
	rm -f *.o run-tests *~
